version: '3'
services:
  demo1:
    build:
      context: ./demo
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - PORT=8001
  demo2:
    build:
      context: ./demo
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    environment:
      - PORT=8002
  demo3:
    build:
      context: ./demo
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    environment:
      - PORT=8003

  nginx:
    image: nginx
    volumes:
      - ./nginx/demo.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8090:8090
    depends_on:
      - demo1
      - demo2
      - demo3
      